### ISSUE TITLE
Possible to replace Gruntjs step with Hugo generated JSON [comment on your Lunrjs blog post]

### ISSUE THREAD

**Issue by kaushalmodi** [bartdegoede/blog#1]
Hello,

Thanks for the detailed writeup. I recently added search to my [site][1] that's based on Fuse.js, using the instructions [here][2]. 

That flow also requires generation of a search index JSON file which I do using this 5-line [`search.json`][3] template (that inherently ignores drafted posts and such). The generated index.json is [here][4].

So I was wondering if the same method of using Hugo itself to generate the JSON was possible in your flow too... Then we wouldn't need Grunt as a dependency (which would be very nice especially for folks like me who are not familiar with Grunt/Gulp/etc tool chain, and JS in general). 

Just my few thoughts, thanks for the write-up!

[1]: https://scripter.co/search/?q=hugo
[2]: https://discourse.gohugo.io/t/site-search-implemented-using-just-hugo-js-no-gulp-grunt-etc/10947
[3]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/master/layouts/_default/search.json
[4]: https://scripter.co/search/index.json

**Comment by bartdegoede** [comment]
I finally got around to actually fixing this using [Output Formats](https://gohugo.io/templates/output-formats/#output-formats-for-pages) (see the [post](https://bart.degoe.de/use-hugo-output-formats-to-generate-lunr-index-files/) too).

It's so nice to drop the dependency on node 😄
